### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by uhgenie7** [uhj1993/portfolio2022#21]
# 개요

Card Component

# 할 일

- [x] Style

# 스토리북 (필요 시)

[storybook](https://www.chromatic.com/component?appId=62e1e051496c124c91b6e054&csfId=atom-card&buildNumber=10&k=62e2158a25408f0f0d8b9959-1200-interactive-true&h=4&b=-1)
[storybook](https://www.chromatic.com/component?appId=62e1e051496c124c91b6e054&csfId=atom-imagecard&buildNumber=10&k=62e2158a25408f0f0d8b995b-1200-interactive-true&h=4&b=-1)

# 래퍼런스
[svg 참고 사이트] (https://iconmonstr.com/share-11-svg/)

**Comment by uhj1993** [comment]
svg 참고 사이트 : https://iconmonstr.com/share-11-svg/
